"use client";
import Header from "./components/common/module/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles.css";
import dynamic from "next/dynamic";
import { parseCookies } from "nookies";
import App from "./components/common/module/menu";
import Profile from "./components/common/module/profile";
import Footer from "./components/common/module/footer";

const ReduxProvider = dynamic(() => import("@/redux/redux-provider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <header>{parseCookies().message === "SUCCESS" && <Header />}</header>
          <main>
            <App />
            <Profile />
            {children}
          </main>
          <footer className="footer">
            <Footer />
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
